In [1]:
!pip3 install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.4.5)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [2]:
# Pandas Dataframe --> 2D Numpy array

In [3]:
# DataFrame is part of pandas?
# To store any data in table format we use dataframe

In [4]:
# source of data
# 1. csv file
# 2. txt file
# 3. excel file
# 4. json file
# 5 python list/dict
# 6 Numpy array
# 7 ....

In [5]:
import pandas as pd

In [6]:
# Dict
data = {
    "Name": ['Mohit', 'Karan', 'Aman'],
    "Age": [20, 30, 40],
    "Salary": [5, 10, 15],
    "Address": ["M1", None ,"A1"]
}

df = pd.DataFrame(data)
df

    Name  Age  Salary
0  Mohit   20       5
1  Karan   30      10
2   Aman   40      15

In [7]:
df = pd.DataFrame(data, index=['E1', 'E2', 'E3'])
df

     Name  Age  Salary
E1  Mohit   20       5
E2  Karan   30      10
E3   Aman   40      15

In [9]:
# List
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10, "Address": "M1"},
    {"Name": "Karan", "Age": 30, "Salary": 20, "PhoneNumber": 20304034},
    {"Name": "Aman", "Age": 35, "Salary": 25, "Address": "A1"}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary Address  PhoneNumber
0  Mohit   20      10      M1          NaN
1  Karan   30      20     NaN   20304034.0
2   Aman   35      25      A1          NaN

In [10]:
# Convert Numpy array to DataFrame
import numpy as np
data = np.array([[25, 1000], [30, 3500], [40, 4500]])
df = pd.DataFrame(data, columns=['Age', 'Salary'], index=['Mohit', 'Karan', 'Aman'])
df

       Age  Salary
Mohit   25    1000
Karan   30    3500
Aman    40    4500

In [12]:
# Empty DataFrame with columns
df = pd.DataFrame(columns=['Name', 'Age', 'Salary'])
df.loc[0] = ['Mohit', 20, 1000]
df.loc[1] = ['Karan', 30, 3500]
df.loc[2] = ['Aman', 40, 4500]
df

    Name  Age  Salary
0  Mohit   20    1000
1  Karan   30    3500
2   Aman   40    4500

In [14]:
# Sales Data Analysis

data = {
    'Month': ['Jan', 'Feb', 'Mar'],
    'Region A': [1000, 2000, 3000],
    'Region B': [4050, 5500, 6100],
    'Region C': [720, 800, 9500]
}
df = pd.DataFrame(data)
df

  Month  Region A  Region B  Region C
0   Jan      1000      4050       720
1   Feb      2000      5500       800
2   Mar      3000      6100      9500

In [15]:
# Adding new column called Total Sales
df['Total Sales'] = df['Region A'] + df['Region B'] + df['Region C']
df

  Month  Region A  Region B  Region C  Total Sales
0   Jan      1000      4050       720         5770
1   Feb      2000      5500       800         8300
2   Mar      3000      6100      9500        18600

In [16]:
# Add avg sales
df["Avg Sales"] = df["Total Sales"] / 3
df

  Month  Region A  Region B  Region C  Total Sales    Avg Sales
0   Jan      1000      4050       720         5770  1923.333333
1   Feb      2000      5500       800         8300  2766.666667
2   Mar      3000      6100      9500        18600  6200.000000

In [17]:
# How to delete and insert data in Pandas DataFrame

In [18]:
# drop() method is used to delete data from DataFrame
# label ==> column name, index name
# axis = 0 row (default), 1 column
# inplace = True/False --> default is False, if True then changes will be made in original DataFrame
# error = 'ignore'/'raise' --> default is 'raise', if 'ignore' then no error will be raised if label not found

In [19]:
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10, "Address": "M1"},
    {"Name": "Karan", "Age": 30, "Salary": 20, "PhoneNumber": 20304034},
    {"Name": "Aman", "Age": 35, "Salary": 25, "Address": "A1"}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary Address  PhoneNumber
0  Mohit   20      10      M1          NaN
1  Karan   30      20     NaN   20304034.0
2   Aman   35      25      A1          NaN

In [20]:
# I want to delete the Karan row
df_dropped = df.drop(labels=1, axis=0)
df_dropped

    Name  Age  Salary Address  PhoneNumber
0  Mohit   20      10      M1          NaN
2   Aman   35      25      A1          NaN

In [21]:
# Pass multiple index to delete row
df_dropped = df.drop(labels=[0, 2], axis=0)
df_dropped

    Name  Age  Salary Address  PhoneNumber
1  Karan   30      20     NaN   20304034.0

In [22]:
# Delete a column
df_dropped = df.drop(labels='Salary', axis=1)
df_dropped

    Name  Age Address  PhoneNumber
0  Mohit   20      M1          NaN
1  Karan   30     NaN   20304034.0
2   Aman   35      A1          NaN

In [23]:
df_dropped = df.drop(labels=['Salary', 'Address'], axis=1)
df_dropped

    Name  Age  PhoneNumber
0  Mohit   20          NaN
1  Karan   30   20304034.0
2   Aman   35          NaN

In [24]:
# Delete using del keyword of python
del df['Salary']
df

    Name  Age Address  PhoneNumber
0  Mohit   20      M1          NaN
1  Karan   30     NaN   20304034.0
2   Aman   35      A1          NaN

In [26]:
df_dropped = df.drop(labels=['Salary', 'Address'], axis=1, errors='ignore')
df_dropped

    Name  Age  PhoneNumber
0  Mohit   20          NaN
1  Karan   30   20304034.0
2   Aman   35          NaN