In [1]:
!pip3 install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.4.5)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [2]:
# Pandas Dataframe --> 2D Numpy array

In [3]:
# DataFrame is part of pandas?
# To store any data in table format we use dataframe

In [4]:
# source of data
# 1. csv file
# 2. txt file
# 3. excel file
# 4. json file
# 5 python list/dict
# 6 Numpy array
# 7 ....

In [5]:
import pandas as pd

In [6]:
# Dict
data = {
    "Name": ['Mohit', 'Karan', 'Aman'],
    "Age": [20, 30, 40],
    "Salary": [5, 10, 15],
    "Address": ["M1", None ,"A1"]
}

df = pd.DataFrame(data)
df

    Name  Age  Salary Address
0  Mohit   20       5      M1
1  Karan   30      10     NaN
2   Aman   40      15      A1

In [7]:
df = pd.DataFrame(data, index=['E1', 'E2', 'E3'])
df

     Name  Age  Salary Address
E1  Mohit   20       5      M1
E2  Karan   30      10     NaN
E3   Aman   40      15      A1

In [8]:
# List
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10, "Address": "M1"},
    {"Name": "Karan", "Age": 30, "Salary": 20, "PhoneNumber": 20304034},
    {"Name": "Aman", "Age": 35, "Salary": 25, "Address": "A1"}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary Address  PhoneNumber
0  Mohit   20      10      M1          NaN
1  Karan   30      20     NaN   20304034.0
2   Aman   35      25      A1          NaN

In [9]:
# Convert Numpy array to DataFrame
import numpy as np
data = np.array([[25, 1000], [30, 3500], [40, 4500]])
df = pd.DataFrame(data, columns=['Age', 'Salary'], index=['Mohit', 'Karan', 'Aman'])
df

       Age  Salary
Mohit   25    1000
Karan   30    3500
Aman    40    4500

In [10]:
# Empty DataFrame with columns
df = pd.DataFrame(columns=['Name', 'Age', 'Salary'])
df.loc[0] = ['Mohit', 20, 1000]
df.loc[1] = ['Karan', 30, 3500]
df.loc[2] = ['Aman', 40, 4500]
df

    Name  Age  Salary
0  Mohit   20    1000
1  Karan   30    3500
2   Aman   40    4500

In [11]:
# Sales Data Analysis

data = {
    'Month': ['Jan', 'Feb', 'Mar'],
    'Region A': [1000, 2000, 3000],
    'Region B': [4050, 5500, 6100],
    'Region C': [720, 800, 9500]
}
df = pd.DataFrame(data)
df

  Month  Region A  Region B  Region C
0   Jan      1000      4050       720
1   Feb      2000      5500       800
2   Mar      3000      6100      9500

In [12]:
# Adding new column called Total Sales
df['Total Sales'] = df['Region A'] + df['Region B'] + df['Region C']
df

  Month  Region A  Region B  Region C  Total Sales
0   Jan      1000      4050       720         5770
1   Feb      2000      5500       800         8300
2   Mar      3000      6100      9500        18600

In [13]:
# Add avg sales
df["Avg Sales"] = df["Total Sales"] / 3
df

  Month  Region A  Region B  Region C  Total Sales    Avg Sales
0   Jan      1000      4050       720         5770  1923.333333
1   Feb      2000      5500       800         8300  2766.666667
2   Mar      3000      6100      9500        18600  6200.000000

In [14]:
# How to delete and insert data in Pandas DataFrame

In [15]:
# drop() method is used to delete data from DataFrame
# label ==> column name, index name
# axis = 0 row (default), 1 column
# inplace = True/False --> default is False, if True then changes will be made in original DataFrame
# error = 'ignore'/'raise' --> default is 'raise', if 'ignore' then no error will be raised if label not found

In [16]:
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10, "Address": "M1"},
    {"Name": "Karan", "Age": 30, "Salary": 20, "PhoneNumber": 20304034},
    {"Name": "Aman", "Age": 35, "Salary": 25, "Address": "A1"}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary Address  PhoneNumber
0  Mohit   20      10      M1          NaN
1  Karan   30      20     NaN   20304034.0
2   Aman   35      25      A1          NaN

In [17]:
# I want to delete the Karan row
df_dropped = df.drop(labels=1, axis=0)
df_dropped

    Name  Age  Salary Address  PhoneNumber
0  Mohit   20      10      M1          NaN
2   Aman   35      25      A1          NaN

In [18]:
# Pass multiple index to delete row
df_dropped = df.drop(labels=[0, 2], axis=0)
df_dropped

    Name  Age  Salary Address  PhoneNumber
1  Karan   30      20     NaN   20304034.0

In [19]:
# Delete a column
df_dropped = df.drop(labels='Salary', axis=1)
df_dropped

    Name  Age Address  PhoneNumber
0  Mohit   20      M1          NaN
1  Karan   30     NaN   20304034.0
2   Aman   35      A1          NaN

In [20]:
df_dropped = df.drop(labels=['Salary', 'Address'], axis=1)
df_dropped

    Name  Age  PhoneNumber
0  Mohit   20          NaN
1  Karan   30   20304034.0
2   Aman   35          NaN

In [21]:
# Delete using del keyword of python
del df['Salary']
df

    Name  Age Address  PhoneNumber
0  Mohit   20      M1          NaN
1  Karan   30     NaN   20304034.0
2   Aman   35      A1          NaN

In [22]:
df_dropped = df.drop(labels=['Salary', 'Address'], axis=1, errors='ignore')
df_dropped

    Name  Age  PhoneNumber
0  Mohit   20          NaN
1  Karan   30   20304034.0
2   Aman   35          NaN

In [23]:
# Insert
# insert()
# assign()
# direct assignment

In [24]:
# insert() --> Use to add column
# df.insert(loc, column, value, allow_duplicates=False)
# Loc --> index of column where new column will be inserted
# column --> name of new column
# value --> value of new column
# allow_duplicates --> default is False, if True then duplicate column name will be allowed

In [25]:
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10},
    {"Name": "Karan", "Age": 30, "Salary": 20},
    {"Name": "Aman", "Age": 35, "Salary": 25}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary
0  Mohit   20      10
1  Karan   30      20
2   Aman   35      25

In [26]:
df.insert(loc=1, column='Address', value=['M1', 'A1', 'A1'], allow_duplicates=True)
df

    Name Address  Age  Salary
0  Mohit      M1   20      10
1  Karan      A1   30      20
2   Aman      A1   35      25

In [27]:
df['Score'] = [90, 80, 70]
df

    Name Address  Age  Salary  Score
0  Mohit      M1   20      10     90
1  Karan      A1   30      20     80
2   Aman      A1   35      25     70

In [28]:
# assign() -> create new dataframe with the added column

new_df = df.assign(PhoneNumber=[1234567890, 9876543210, 1122334455])
new_df

    Name Address  Age  Salary  Score  PhoneNumber
0  Mohit      M1   20      10     90   1234567890
1  Karan      A1   30      20     80   9876543210
2   Aman      A1   35      25     70   1122334455

In [29]:
df

    Name Address  Age  Salary  Score
0  Mohit      M1   20      10     90
1  Karan      A1   30      20     80
2   Aman      A1   35      25     70

In [30]:
# How to insert a row in Pandas DataFrame
# loc or iloc can be used to insert a row in Pandas DataFrame

In [31]:
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10},
    {"Name": "Karan", "Age": 30, "Salary": 20},
    {"Name": "Aman", "Age": 35, "Salary": 25}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary
0  Mohit   20      10
1  Karan   30      20
2   Aman   35      25

In [32]:
new_row = {"Name": "Rohit", "Age": 28, "Salary": 15}
df.loc[3] = new_row

In [33]:
df

    Name  Age  Salary
0  Mohit   20      10
1  Karan   30      20
2   Aman   35      25
3  Rohit   28      15

In [34]:
new_row = {"Name": "Arjun", "Age": 28, "Salary": 34}
df.iloc[0] = new_row # It will insert the data at position 0 and shift the rest of the rows down

In [35]:
df

    Name  Age  Salary
0  Arjun   28      34
1  Karan   30      20
2   Aman   35      25
3  Rohit   28      15

In [36]:
# append() -> create a new dataframe with the added row
# new_row = {"Name": "BlaBla", "Age": 444, "Salary": 444565}
# new_row_df = pd.DataFrame(new_row)
# df_new = df.append(new_row_df, ignore_index=True)
# df_new

In [37]:
# concat() -> is a pandas function used to add two dataframes together. It can be used to add rows or columns to a dataframe.
new_row = [{"Name": "BlaBla", "Age": 444, "Salary": 444565}]
new_row_df = pd.DataFrame(new_row)
new_row_df

     Name  Age  Salary
0  BlaBla  444  444565

In [38]:
result_df = pd.concat([df, new_row_df], ignore_index=True)
result_df

     Name  Age  Salary
0   Arjun   28      34
1   Karan   30      20
2    Aman   35      25
3   Rohit   28      15
4  BlaBla  444  444565

In [39]:
# Read & Write DataFrame to CSV file

df = pd.read_csv("data/sample_data.csv")
df

   ID            Name  Age   Salary   Department
0   1        John Doe   28  55000.0  Engineering
1   2      Jane Smith   34  62000.0    Marketing
2   3     Bob Johnson   45  75000.0        Sales
3   4  Alice Williams   29      NaN  Engineering

In [40]:
# use the 'ID' column as index
df = pd.read_csv("data/sample_data.csv", index_col='ID')
df

              Name  Age   Salary   Department
ID
1         John Doe   28  55000.0  Engineering
2       Jane Smith   34  62000.0    Marketing
3      Bob Johnson   45  75000.0        Sales
4   Alice Williams   29      NaN  Engineering

In [41]:
df = pd.read_csv("data/sample_data.csv", index_col='ID', usecols=['ID','Name', 'Salary'])
print(df)

              Name   Salary
ID
1         John Doe  55000.0
2       Jane Smith  62000.0
3      Bob Johnson  75000.0
4   Alice Williams      NaN

In [42]:
df = pd.read_csv("data/sample_data.csv")
print(df)

   ID            Name  Age   Salary   Department
0   1        John Doe   28  55000.0  Engineering
1   2      Jane Smith   34  62000.0    Marketing
2   3     Bob Johnson   45  75000.0        Sales
3   4  Alice Williams   29      NaN  Engineering

In [43]:
# Write DataFrame to CSV file
df.to_csv("data/sample_data_output.csv", index=False)

In [44]:
# write specific columns
new_df = df[['Name', 'Salary']]
new_df.to_csv("data/sample_data_output.csv", index=False)

In [45]:
# write data using custom sep
df.to_csv("data/sample_data_output.csv", sep='|', index=False)

In [46]:
# write without header
df.to_csv("data/sample_data_output.csv", index=False, header=False)

In [47]:
# Advance read and write
df = pd.read_csv("data/sample_data.csv", skiprows=2)
print(df)

   2      Jane Smith  34    62000    Marketing
0  3     Bob Johnson  45  75000.0        Sales
1  4  Alice Williams  29      NaN  Engineering

In [48]:
chunk_size = 2

for chunk in pd.read_csv("data/sample_data.csv", chunksize=chunk_size):
    print(chunk)

   ID        Name  Age  Salary   Department
0   1    John Doe   28   55000  Engineering
1   2  Jane Smith   34   62000    Marketing
   ID            Name  Age   Salary   Department
2   3     Bob Johnson   45  75000.0        Sales
3   4  Alice Williams   29      NaN  Engineering

In [49]:
# compress the data
df.to_csv("data/sample_data_output.csv.gz", compression='gzip',index=False)

In [50]:
# Data Operation in Pandas
# Data Creation (Extract)
# Data inspection  (Transform) -->(Debugging, Filter)
# Data Selection
# Data Cleaning  (Transform)
# Data Transformation
# Data Aggregation
# Data Visualization --> Matplotlib

# ETL --> Extract, Transform, Load

In [51]:
# customer purchase info
# Data Creation
data = {
    "Customer_ID": [101, 102, 103, 104, 105],
    "Name": ['Mohit', 'Karan', 'Aman', 'Arjun', 'Ajay'],
    "Age": [10, 20, 30, 40, 50],
    "Total_Purchase": [10, 20, 30, 40, 50],
    "Country": ["USA", "CANADA", "USA", "UK", "CANADA"],
}

df = pd.DataFrame(data)
df

   Customer_ID   Name  Age  Total_Purchase Country
0          101  Mohit   10              10     USA
1          102  Karan   20              20  CANADA
2          103   Aman   30              30     USA
3          104  Arjun   40              40      UK
4          105   Ajay   50              50  CANADA

In [52]:
 # Data inspection (debugging)
 df.head(2) # first 5 rows

   Customer_ID   Name  Age  Total_Purchase Country
0          101  Mohit   10              10     USA
1          102  Karan   20              20  CANADA

In [53]:
df.tail(2) # last 5 rows

   Customer_ID   Name  Age  Total_Purchase Country
3          104  Arjun   40              40      UK
4          105   Ajay   50              50  CANADA

In [54]:
df.info() # info about the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     5 non-null      int64
 1   Name            5 non-null      str
 2   Age             5 non-null      int64
 3   Total_Purchase  5 non-null      int64
 4   Country         5 non-null      str
dtypes: int64(3), str(2)
memory usage: 332.0 bytes

In [55]:
df.describe() # statistical summary of the dataframe

       Customer_ID        Age  Total_Purchase
count     5.000000   5.000000        5.000000
mean    103.000000  30.000000       30.000000
std       1.581139  15.811388       15.811388
min     101.000000  10.000000       10.000000
25%     102.000000  20.000000       20.000000
50%     103.000000  30.000000       30.000000
75%     104.000000  40.000000       40.000000
max     105.000000  50.000000       50.000000

In [56]:
# See all the name
# Dataframe column is a Series
df['Name'] # Series

0    Mohit
1    Karan
2     Aman
3    Arjun
4     Ajay
Name: Name, dtype: str

In [57]:
# Dataframe if you are selecting more then 1 column it returns a DataFrame
df[['Name', 'Age']]

    Name  Age
0  Mohit   10
1  Karan   20
2   Aman   30
3  Arjun   40
4   Ajay   50

In [58]:
# iloc (Row position based selection) and loc (Row label based selection)
df.iloc[0:2]

   Customer_ID   Name  Age  Total_Purchase Country
0          101  Mohit   10              10     USA
1          102  Karan   20              20  CANADA

In [59]:
df.loc[0:2]

   Customer_ID   Name  Age  Total_Purchase Country
0          101  Mohit   10              10     USA
1          102  Karan   20              20  CANADA
2          103   Aman   30              30     USA

In [60]:
# Filter row, conditional statement
df[df['Total_Purchase'] > 30]

   Customer_ID   Name  Age  Total_Purchase Country
3          104  Arjun   40              40      UK
4          105   Ajay   50              50  CANADA

In [61]:
# Selecting specific column with a filter
df.loc[df['Age'] > 20, ['Name', 'Age']]

    Name  Age
2   Aman   30
3  Arjun   40
4   Ajay   50

In [62]:
# Data Cleaning
# 1. Handling missing values
# 2. Handling duplicate values
# 3. Handle Incorrect data
# 4. Column renaming & ordering
# 5. Data type conversion

In [63]:
df = pd.read_csv("data/student.csv")
df

   ID            Name   Age  Math    Science   English  History
0   1        John Doe  28.0  85.0         90        78     88.0
1   2      jane Smith  34.0  92.0  Not Found        88      NaN
2   3     Bob Johnson  45.0  75.0         80        70     72.0
3   4  Alice Williams  29.0   NaN         92        85     90.0
4   5   charlie Brown  31.0   NaN         75        82     78.0
5   3     Bob Johnson  45.0  75.0         80        70     72.0
6   6       david Lee   NaN  88.0         90  No Score     87.0

In [64]:
# Handle Missing values
df.isnull() # check for missing values

      ID   Name    Age   Math  Science  English  History
0  False  False  False  False    False    False    False
1  False  False  False  False    False    False     True
2  False  False  False  False    False    False    False
3  False  False  False   True    False    False    False
4  False  False  False   True    False    False    False
5  False  False  False  False    False    False    False
6  False  False   True  False    False    False    False

In [65]:
# Drop the null data row
df_cleared = df.dropna()
df_cleared

   ID         Name   Age  Math Science English  History
0   1     John Doe  28.0  85.0      90      78     88.0
2   3  Bob Johnson  45.0  75.0      80      70     72.0
5   3  Bob Johnson  45.0  75.0      80      70     72.0

In [66]:
# Fill the null data with a specific value
df['Math'] = df['Math'].fillna(df['Math'].mean())
df

   ID            Name   Age  Math    Science   English  History
0   1        John Doe  28.0  85.0         90        78     88.0
1   2      jane Smith  34.0  92.0  Not Found        88      NaN
2   3     Bob Johnson  45.0  75.0         80        70     72.0
3   4  Alice Williams  29.0  83.0         92        85     90.0
4   5   charlie Brown  31.0  83.0         75        82     78.0
5   3     Bob Johnson  45.0  75.0         80        70     72.0
6   6       david Lee   NaN  88.0         90  No Score     87.0

In [67]:
# Replace value with interpolation function
df['History'] = df['History'].interpolate()
df

   ID            Name   Age  Math    Science   English  History
0   1        John Doe  28.0  85.0         90        78     88.0
1   2      jane Smith  34.0  92.0  Not Found        88     80.0
2   3     Bob Johnson  45.0  75.0         80        70     72.0
3   4  Alice Williams  29.0  83.0         92        85     90.0
4   5   charlie Brown  31.0  83.0         75        82     78.0
5   3     Bob Johnson  45.0  75.0         80        70     72.0
6   6       david Lee   NaN  88.0         90  No Score     87.0

In [68]:
# Handle Duplicate values

duplicates = df.duplicated()
duplicates

0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [69]:
df_no_duplicates = df.drop_duplicates()
df_no_duplicates

   ID            Name   Age  Math    Science   English  History
0   1        John Doe  28.0  85.0         90        78     88.0
1   2      jane Smith  34.0  92.0  Not Found        88     80.0
2   3     Bob Johnson  45.0  75.0         80        70     72.0
3   4  Alice Williams  29.0  83.0         92        85     90.0
4   5   charlie Brown  31.0  83.0         75        82     78.0
6   6       david Lee   NaN  88.0         90  No Score     87.0

In [70]:
# Replace Incorrect data or Inconsistent data
df = pd.read_csv("data/student.csv")
df.replace(['No Score', 'Not Found'], pd.NA, inplace=True)
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       7 non-null      int64
 1   Name     7 non-null      str
 2   Age      6 non-null      float64
 3   Math     5 non-null      float64
 4   Science  6 non-null      str
 5   English  6 non-null      str
 6   History  6 non-null      float64
dtypes: float64(3), int64(1), str(3)
memory usage: 524.0 bytes
None

In [71]:
print(df)

   ID            Name   Age  Math Science English  History
0   1        John Doe  28.0  85.0      90      78     88.0
1   2      jane Smith  34.0  92.0     NaN      88      NaN
2   3     Bob Johnson  45.0  75.0      80      70     72.0
3   4  Alice Williams  29.0   NaN      92      85     90.0
4   5   charlie Brown  31.0   NaN      75      82     78.0
5   3     Bob Johnson  45.0  75.0      80      70     72.0
6   6       david Lee   NaN  88.0      90     NaN     87.0

In [72]:
# Correct data format
df['Name'] = df['Name'].str.title()
print(df)

   ID            Name   Age  Math Science English  History
0   1        John Doe  28.0  85.0      90      78     88.0
1   2      Jane Smith  34.0  92.0     NaN      88      NaN
2   3     Bob Johnson  45.0  75.0      80      70     72.0
3   4  Alice Williams  29.0   NaN      92      85     90.0
4   5   Charlie Brown  31.0   NaN      75      82     78.0
5   3     Bob Johnson  45.0  75.0      80      70     72.0
6   6       David Lee   NaN  88.0      90     NaN     87.0

In [73]:
# Renaming & Reordering Columns
# Use case 1: cosmetic so to make column name more meaning full
# Use case 2: it helps in merge or concat two dataframe
# Use case3: to prevet save operation of database (scheme match)
df = df.rename(columns={'Math': 'Math_Score', 'History': 'History_Score'})
print(df)

   ID            Name   Age  Math_Score Science English  History_Score
0   1        John Doe  28.0        85.0      90      78           88.0
1   2      Jane Smith  34.0        92.0     NaN      88            NaN
2   3     Bob Johnson  45.0        75.0      80      70           72.0
3   4  Alice Williams  29.0         NaN      92      85           90.0
4   5   Charlie Brown  31.0         NaN      75      82           78.0
5   3     Bob Johnson  45.0        75.0      80      70           72.0
6   6       David Lee   NaN        88.0      90     NaN           87.0

In [74]:
# Rearrange the column order
df = df[['Age', 'ID', 'History_Score', 'Math_Score', 'Name']]
print(df)

    Age  ID  History_Score  Math_Score            Name
0  28.0   1           88.0        85.0        John Doe
1  34.0   2            NaN        92.0      Jane Smith
2  45.0   3           72.0        75.0     Bob Johnson
3  29.0   4           90.0         NaN  Alice Williams
4  31.0   5           78.0         NaN   Charlie Brown
5  45.0   3           72.0        75.0     Bob Johnson
6   NaN   6           87.0        88.0       David Lee

In [76]:
# ETL
# Merge & Concat

# merge() --> is used to combine two dataframes based on a common column or index.
#pd.merge(left, right, how='inner', on=None, left_on=None,right_on=None)
# left, right --> two dataframes to be merged
# on --> column name to merge on
# how --> type of merge to be performed (inner, outer, left, right)
# how='inner' --> only the rows with matching values in both dataframes will be included in the result
# left_on --> column name in left dataframe to merge on
# right_on --> column name in right dataframe to merge on

In [81]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5, 6],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Mohit', 'Karan'],
})
df1

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5    Mohit
5   6    Karan

In [85]:
df2 = pd.DataFrame({
    'ID': [1, 2, 3, 44],
    'Score': [25, 30, 35, 40],
})
df2

   ID  Score
0   1     25
1   2     30
2   3     35
3  44     40

In [86]:
# Inner Join
# Only row with matching key (on='ID') are included
result = pd.merge(df1, df2, on='ID', how='inner')
result

   ID     Name  Score
0   1    Alice     25
1   2      Bob     30
2   3  Charlie     35

In [87]:
# Left Join
# All rows from the left df
result = pd.merge(df1, df2, on='ID', how='left')
result

   ID     Name  Score
0   1    Alice   25.0
1   2      Bob   30.0
2   3  Charlie   35.0
3   4    David    NaN
4   5    Mohit    NaN
5   6    Karan    NaN

In [88]:
# Right Join
# All rows from the right df is included
result = pd.merge(df1, df2, on='ID', how='right')
result

   ID     Name  Score
0   1    Alice     25
1   2      Bob     30
2   3  Charlie     35
3  44      NaN     40

In [89]:
# Outer Join
# All rows from both df are included
# Outer = left + right
result = pd.merge(df1, df2, on='ID', how='outer')
result

   ID     Name  Score
0   1    Alice   25.0
1   2      Bob   30.0
2   3  Charlie   35.0
3   4    David    NaN
4   5    Mohit    NaN
5   6    Karan    NaN
6  44      NaN   40.0

In [90]:
# Merge on multiple keys
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Subject': ['Science', 'Math', 'History'],
    'Score': [2, 4, 6]
})
df1

   ID  Subject  Score
0   1  Science      2
1   2     Math      4
2   3  History      6

In [91]:
df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Subject': ['Math', 'History', 'English'],
    'Grade': ['A', 'B', 'C']
})
df2

   ID  Subject Grade
0   2     Math     A
1   3  History     B
2   4  English     C

In [92]:
result = pd.merge(df1, df2, on=['ID', 'Subject'], how='inner')
result

   ID  Subject  Score Grade
0   2     Math      4     A
1   3  History      6     B

In [94]:
# Merge with different column names
df1 = pd.DataFrame({
    'Student_ID': [1, 2, 3],
    'Subject': ['Science', 'Math', 'History'],
    'Score': [2, 4, 6]
})
df1

   Student_ID  Subject  Score
0           1  Science      2
1           2     Math      4
2           3  History      6

In [95]:
df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Subject': ['Math', 'History', 'English'],
    'Grade': ['A', 'B', 'C']
})
df2

   ID  Subject Grade
0   2     Math     A
1   3  History     B
2   4  English     C

In [97]:
result = pd.merge(df1, df2, left_on=['Student_ID', 'Subject'], right_on=['ID', 'Subject'], how='inner')
result

   Student_ID  Subject  Score  ID Grade
0           2     Math      4   2     A
1           3  History      6   3     B

In [98]:
# concat
# used for combine two or more dataframes along a axis (row-wise or column-wise).
# pd.concat(objs, axis=0, keys=None, ignore_index=False)
# objs --> list of dataframes to be concatenated

In [99]:
df1 = pd.DataFrame({
    'ID': [1, 2],
    'Name': ['Alice', 'Bob'],
})
df1

   ID   Name
0   1  Alice
1   2    Bob

In [100]:
df2 = pd.DataFrame({
    'ID': [3, 4],
    'Name': ['Mohit', 'Aman'],
})
df2

   ID   Name
0   3  Mohit
1   4   Aman

In [102]:
# Row-wise concat
result = pd.concat([df1, df2], axis=0, ignore_index=True)
result

   ID   Name
0   1  Alice
1   2    Bob
2   3  Mohit
3   4   Aman

In [103]:
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
})
df1

    Name
0  Alice
1    Bob

In [104]:
df2 = pd.DataFrame({
    'Age': [20, 30],
})
df2

   Age
0   20
1   30

In [106]:
# Column-wise concat
result = pd.concat([df1, df2], axis=1)
result

    Name  Age
0  Alice   20
1    Bob   30

In [110]:
df1 = pd.DataFrame({
    'ID': [1, 2],
    'Name': ['Alice', 'Bob'],
})
df1

   ID   Name
0   1  Alice
1   2    Bob

In [111]:
df2 = pd.DataFrame({
    'ID': [22, 33],
    'Name': ['Mohit', 'Aman'],
})
df2

   ID   Name
0  22  Mohit
1  33   Aman

In [112]:
# Concat with keys (to create hierarchical)
result = pd.concat([df1, df2], axis=0, keys=['Finance', 'Technology'])
result

              ID   Name
Finance    0   1  Alice
           1   2    Bob
Technology 0  22  Mohit
           1  33   Aman