In [1]:
!pip3 install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.4.5)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [2]:
# Pandas Dataframe --> 2D Numpy array

In [3]:
# DataFrame is part of pandas?
# To store any data in table format we use dataframe

In [4]:
# source of data
# 1. csv file
# 2. txt file
# 3. excel file
# 4. json file
# 5 python list/dict
# 6 Numpy array
# 7 ....

In [5]:
import pandas as pd

In [6]:
# Dict
data = {
    "Name": ['Mohit', 'Karan', 'Aman'],
    "Age": [20, 30, 40],
    "Salary": [5, 10, 15],
    "Address": ["M1", None ,"A1"]
}

df = pd.DataFrame(data)
df

    Name  Age  Salary Address
0  Mohit   20       5      M1
1  Karan   30      10     NaN
2   Aman   40      15      A1

In [7]:
df = pd.DataFrame(data, index=['E1', 'E2', 'E3'])
df

     Name  Age  Salary Address
E1  Mohit   20       5      M1
E2  Karan   30      10     NaN
E3   Aman   40      15      A1

In [8]:
# List
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10, "Address": "M1"},
    {"Name": "Karan", "Age": 30, "Salary": 20, "PhoneNumber": 20304034},
    {"Name": "Aman", "Age": 35, "Salary": 25, "Address": "A1"}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary Address  PhoneNumber
0  Mohit   20      10      M1          NaN
1  Karan   30      20     NaN   20304034.0
2   Aman   35      25      A1          NaN

In [9]:
# Convert Numpy array to DataFrame
import numpy as np
data = np.array([[25, 1000], [30, 3500], [40, 4500]])
df = pd.DataFrame(data, columns=['Age', 'Salary'], index=['Mohit', 'Karan', 'Aman'])
df

       Age  Salary
Mohit   25    1000
Karan   30    3500
Aman    40    4500

In [10]:
# Empty DataFrame with columns
df = pd.DataFrame(columns=['Name', 'Age', 'Salary'])
df.loc[0] = ['Mohit', 20, 1000]
df.loc[1] = ['Karan', 30, 3500]
df.loc[2] = ['Aman', 40, 4500]
df

    Name  Age  Salary
0  Mohit   20    1000
1  Karan   30    3500
2   Aman   40    4500

In [11]:
# Sales Data Analysis

data = {
    'Month': ['Jan', 'Feb', 'Mar'],
    'Region A': [1000, 2000, 3000],
    'Region B': [4050, 5500, 6100],
    'Region C': [720, 800, 9500]
}
df = pd.DataFrame(data)
df

  Month  Region A  Region B  Region C
0   Jan      1000      4050       720
1   Feb      2000      5500       800
2   Mar      3000      6100      9500

In [12]:
# Adding new column called Total Sales
df['Total Sales'] = df['Region A'] + df['Region B'] + df['Region C']
df

  Month  Region A  Region B  Region C  Total Sales
0   Jan      1000      4050       720         5770
1   Feb      2000      5500       800         8300
2   Mar      3000      6100      9500        18600

In [13]:
# Add avg sales
df["Avg Sales"] = df["Total Sales"] / 3
df

  Month  Region A  Region B  Region C  Total Sales    Avg Sales
0   Jan      1000      4050       720         5770  1923.333333
1   Feb      2000      5500       800         8300  2766.666667
2   Mar      3000      6100      9500        18600  6200.000000

In [14]:
# How to delete and insert data in Pandas DataFrame

In [15]:
# drop() method is used to delete data from DataFrame
# label ==> column name, index name
# axis = 0 row (default), 1 column
# inplace = True/False --> default is False, if True then changes will be made in original DataFrame
# error = 'ignore'/'raise' --> default is 'raise', if 'ignore' then no error will be raised if label not found

In [16]:
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10, "Address": "M1"},
    {"Name": "Karan", "Age": 30, "Salary": 20, "PhoneNumber": 20304034},
    {"Name": "Aman", "Age": 35, "Salary": 25, "Address": "A1"}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary Address  PhoneNumber
0  Mohit   20      10      M1          NaN
1  Karan   30      20     NaN   20304034.0
2   Aman   35      25      A1          NaN

In [17]:
# I want to delete the Karan row
df_dropped = df.drop(labels=1, axis=0)
df_dropped

    Name  Age  Salary Address  PhoneNumber
0  Mohit   20      10      M1          NaN
2   Aman   35      25      A1          NaN

In [18]:
# Pass multiple index to delete row
df_dropped = df.drop(labels=[0, 2], axis=0)
df_dropped

    Name  Age  Salary Address  PhoneNumber
1  Karan   30      20     NaN   20304034.0

In [19]:
# Delete a column
df_dropped = df.drop(labels='Salary', axis=1)
df_dropped

    Name  Age Address  PhoneNumber
0  Mohit   20      M1          NaN
1  Karan   30     NaN   20304034.0
2   Aman   35      A1          NaN

In [20]:
df_dropped = df.drop(labels=['Salary', 'Address'], axis=1)
df_dropped

    Name  Age  PhoneNumber
0  Mohit   20          NaN
1  Karan   30   20304034.0
2   Aman   35          NaN

In [21]:
# Delete using del keyword of python
del df['Salary']
df

    Name  Age Address  PhoneNumber
0  Mohit   20      M1          NaN
1  Karan   30     NaN   20304034.0
2   Aman   35      A1          NaN

In [22]:
df_dropped = df.drop(labels=['Salary', 'Address'], axis=1, errors='ignore')
df_dropped

    Name  Age  PhoneNumber
0  Mohit   20          NaN
1  Karan   30   20304034.0
2   Aman   35          NaN

In [23]:
# Insert
# insert()
# assign()
# direct assignment

In [24]:
# insert() --> Use to add column
# df.insert(loc, column, value, allow_duplicates=False)
# Loc --> index of column where new column will be inserted
# column --> name of new column
# value --> value of new column
# allow_duplicates --> default is False, if True then duplicate column name will be allowed

In [25]:
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10},
    {"Name": "Karan", "Age": 30, "Salary": 20},
    {"Name": "Aman", "Age": 35, "Salary": 25}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary
0  Mohit   20      10
1  Karan   30      20
2   Aman   35      25

In [26]:
df.insert(loc=1, column='Address', value=['M1', 'A1', 'A1'], allow_duplicates=True)
df

    Name Address  Age  Salary
0  Mohit      M1   20      10
1  Karan      A1   30      20
2   Aman      A1   35      25

In [27]:
df['Score'] = [90, 80, 70]
df

    Name Address  Age  Salary  Score
0  Mohit      M1   20      10     90
1  Karan      A1   30      20     80
2   Aman      A1   35      25     70

In [28]:
# assign() -> create new dataframe with the added column

new_df = df.assign(PhoneNumber=[1234567890, 9876543210, 1122334455])
new_df

    Name Address  Age  Salary  Score  PhoneNumber
0  Mohit      M1   20      10     90   1234567890
1  Karan      A1   30      20     80   9876543210
2   Aman      A1   35      25     70   1122334455

In [29]:
df

    Name Address  Age  Salary  Score
0  Mohit      M1   20      10     90
1  Karan      A1   30      20     80
2   Aman      A1   35      25     70

In [30]:
# How to insert a row in Pandas DataFrame
# loc or iloc can be used to insert a row in Pandas DataFrame

In [31]:
data = [
    {"Name": "Mohit", "Age": 20, "Salary": 10},
    {"Name": "Karan", "Age": 30, "Salary": 20},
    {"Name": "Aman", "Age": 35, "Salary": 25}
]
df = pd.DataFrame(data)
df

    Name  Age  Salary
0  Mohit   20      10
1  Karan   30      20
2   Aman   35      25

In [32]:
new_row = {"Name": "Rohit", "Age": 28, "Salary": 15}
df.loc[3] = new_row

In [33]:
df

    Name  Age  Salary
0  Mohit   20      10
1  Karan   30      20
2   Aman   35      25
3  Rohit   28      15

In [34]:
new_row = {"Name": "Arjun", "Age": 28, "Salary": 34}
df.iloc[0] = new_row # It will insert the data at position 0 and shift the rest of the rows down

In [35]:
df

    Name  Age  Salary
0  Arjun   28      34
1  Karan   30      20
2   Aman   35      25
3  Rohit   28      15

In [36]:
# append() -> create a new dataframe with the added row
# new_row = {"Name": "BlaBla", "Age": 444, "Salary": 444565}
# new_row_df = pd.DataFrame(new_row)
# df_new = df.append(new_row_df, ignore_index=True)
# df_new

In [37]:
# concat() -> is a pandas function used to add two dataframes together. It can be used to add rows or columns to a dataframe.
new_row = [{"Name": "BlaBla", "Age": 444, "Salary": 444565}]
new_row_df = pd.DataFrame(new_row)
new_row_df

     Name  Age  Salary
0  BlaBla  444  444565

In [38]:
result_df = pd.concat([df, new_row_df], ignore_index=True)
result_df

     Name  Age  Salary
0   Arjun   28      34
1   Karan   30      20
2    Aman   35      25
3   Rohit   28      15
4  BlaBla  444  444565

In [39]:
# Read & Write DataFrame to CSV file

df = pd.read_csv("data/sample_data.csv")
df

   ID         Name  Age  Salary   Department
0   1     John Doe   28   55000  Engineering
1   2   Jane Smith   34   62000    Marketing
2   3  Bob Johnson   45   75000        Sales

In [40]:
# use the 'ID' column as index
df = pd.read_csv("data/sample_data.csv", index_col='ID')
df

           Name  Age  Salary   Department
ID
1      John Doe   28   55000  Engineering
2    Jane Smith   34   62000    Marketing
3   Bob Johnson   45   75000        Sales

In [45]:
df = pd.read_csv("data/sample_data.csv", index_col='ID', usecols=['ID','Name', 'Salary'])
print(df)

           Name  Salary
ID
1      John Doe   55000
2    Jane Smith   62000
3   Bob Johnson   75000

In [46]:
df = pd.read_csv("data/sample_data.csv")
print(df)

   ID            Name  Age   Salary   Department
0   1        John Doe   28  55000.0  Engineering
1   2      Jane Smith   34  62000.0    Marketing
2   3     Bob Johnson   45  75000.0        Sales
3   4  Alice Williams   29      NaN  Engineering

In [59]:
# Write DataFrame to CSV file
df.to_csv("data/sample_data_output.csv", index=False)

In [53]:
# write specific columns
new_df = df[['Name', 'Salary']]
new_df.to_csv("data/sample_data_output.csv", index=False)

In [56]:
# write data using custom sep
df.to_csv("data/sample_data_output.csv", sep='|', index=False)

In [57]:
# write without header
df.to_csv("data/sample_data_output.csv", index=False, header=False)

In [60]:
# Advance read and write
df = pd.read_csv("data/sample_data.csv", skiprows=2)
print(df)

   2      Jane Smith  34    62000    Marketing
0  3     Bob Johnson  45  75000.0        Sales
1  4  Alice Williams  29      NaN  Engineering

In [61]:
chunk_size = 2

for chunk in pd.read_csv("data/sample_data.csv", chunksize=chunk_size):
    print(chunk)

   ID        Name  Age  Salary   Department
0   1    John Doe   28   55000  Engineering
1   2  Jane Smith   34   62000    Marketing
   ID            Name  Age   Salary   Department
2   3     Bob Johnson   45  75000.0        Sales
3   4  Alice Williams   29      NaN  Engineering

In [62]:
# compress the data
df.to_csv("data/sample_data_output.csv.gz", compression='gzip',index=False)

In [ ]:
# Data Operation in Pandas
# Data Creation
# Data inspection
# Data Selection
# Data Cleaning
# Data Transformation
# Data Aggregation
# Data Visualization --> Matplotlib